name: "Terraform Plan and Apply"

on:
  push:
    branches:
      - dev
      - main
  pull_request:

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: "rhel9_build" # Replace with your Terraform Cloud workspace name

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the Terraform version you are using
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Set Terraform Workspace for Dev
        if: github.ref == 'refs/heads/dev'
        run: echo "TF_WORKSPACE=rhel9_build" >> $GITHUB_ENV

      # - name: Set Terraform Workspace for Production
      #   if: github.ref == 'refs/heads/main'
      #   run: echo "TF_WORKSPACE=rhel9_build_prod" >> $GITHUB_ENV

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -no-color

      # - name: Terraform Apply for Dev
      #   if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
      #   run: |
      #     terraform workspace select dev || terraform workspace new dev
      #     terraform apply -auto-approve -no-color

      # - name: Terraform Apply for Production
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: |
      #     terraform workspace select production || terraform workspace new production
      #     terraform apply -auto-approve -no-color
